[package]
name = "library"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[dependencies]
candle-core = { workspace = true }
candle-nn = { workspace = true }
candle-transformers = { workspace = true }
serde_json = { workspace = true}

#hf
hf-hub = { workspace = true }
tokenizers = { workspace = true }